/*
Auto-generated by: https://github.com/pmndrs/gltfjsx

this is not used in the project
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'


let actions = []

function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./models/parry_1.glb')
  actions = useAnimations(animations, group).actions
  console.log(actions)
  // useEffect(() => {
  //   actions.guard_3_hand.play();
  // })
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Armature" position={[0.01, -0.02, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.03}>
        <primitive object={nodes.Hip_Bone} />
        <skinnedMesh geometry={nodes.Cube.geometry}
          material={materials.mapleWood}
          skeleton={nodes.Cube.skeleton}
          castShadow receiveShadow />
        <skinnedMesh
          name="Man"
          geometry={nodes.Man.geometry}
          material={materials.mapleWood}
          skeleton={nodes.Man.skeleton}
          morphTargetDictionary={nodes.Man.morphTargetDictionary}
          morphTargetInfluences={nodes.Man.morphTargetInfluences}
          receiveShadow
          castShadow
        />
      </group>
    </group>
  )
}
export { Model, actions };

useGLTF.preload('./models/parry_1.glb')
